language: node_js
sudo: false
node_js: stable
addons: 
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin local
env:
  global:
  - secure: Ps+drKOqd5GJo2zhY+XG9NiT6kJZeNs5D8fhqpESq0h8nvKdscJ3uLc8HbEGC7pqBfeLb/Rd4WmVjJF9bQWJ/xvYLlGmCrKN5ybZktfpi+fweOPe1jKGxCl8myxzXiU6CdHdKvrkd35JBc7cy2gdRKB6ROkUR5lcK2bSxa498zolVmruU9MClm5wHyynylivjZMYi+1KLZbktr9jZcILMXBqKSjD78wjryU6A0rd0TgCHe8vZRJEXduPpBuU3x61Eoz3kr1P8pJyZOjZivD149b5ssLqsd12+fywSgnoCOloJSXmJ8aUudPuCpOqmi1tjHPrj+I6OVKWnyZwog74B4Ps9NaeBbIgaZker1ErmWsyMrdDsqKS7hvClHv1ACLad3h+D8nEIef5HtvYIA62GOTM90Ulzx1Uo48ngd/v6itpV8RsD3H1BDgFaf9pG2sg6ExCd+2Lf0MDv02V8Ykuh299JFycNrax4OPUwiOA7KDGjSg5gZVNRWMKluoqK1yxstyzOapYv1/UjisVN/fdSB1gluMZ9eq3z7drC4wSaqzW6uKnU2X122y3JLOZPRKtioY4j9qtmxatH8+57SUx0TuMIf99QK9R5no1dylIoYQrTmPcDnexfjKELBzOdYLX2CIyNe0kNSnnIDl6/9pGvCI7cfqTGIo/dd9M2hGeSuU=
  - secure: XmZL9peZqpFzkCeoliTHk8PbEFwHqlqmbdtjxv/DuJHO7ZbEfmzwLIbqECvX1WpyOKh4d9Jjoll8rsFZAqs2mDcAzyq2P5sLrfBuVI80zNfG3z6dKLUf0I8IxMj/8KiokDEpf+lU5ki25ljMzTTS3GdzsyW0jo+DcGeKTvfb+95GOnmabLp50akvixnPy0g/si9QgcwwUI/T7ffGlcMOxr+OcXOk8Abgp59QnnWjP6NBJA3OiqQECuIQJoYtL1Z7yaBB9A+QoYh5IaO5PnOS2ffDSsFn0SvfieHs61KjxLgKDJuV+DllhEqXhGsKdraGAyhg+yu0SbFXXIcaDdGnzaM3bU02C2eDkmmYwIk6J/TRG2h9iNVB4tqXLNLQyFBVWScXkMzBy8GqVGilQGsO5KjEWv8LddM3pjFu7JBx6JCAN03/qgXryjMp+VsLo70z2KDDosBCThJCDPx6iaSSEnklMVRwZw4ayFVxFyPm6UstD5IlRy8RaX9CHfdLcjfc5uokkMSWKsDk5dO4YCsj0jkqdhMPaPX5PVcju+I+r91EYU1EBO1R1g9wWrMf4xghq8f4qiQgZMdfik1hyP7QXEdFwPWd3nWJXQT6dVoMTj5Fxvj4HVxiqhugGBKqOooqE7/i8jFKPXGxFeu9QVsa/yLfDyBHwOY3J4Nl6QXWgUY=
